name: Local type checking
on: [push]

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps without lockfile
        run: pnpm install --no-lockfile

      - name: "Type check"
        run: pnpm tsc
